say_hello:
  path: "/workflows/say_hello.wdl"
  tests:
    simple:
      test_inputs: "/tests/say_hello/simple_test/test_inputs.json"
      expected_outputs: "/tests/say_hello/simple_test/expected_outputs.json"
    mismatch:
      test_inputs: "/tests/say_hello/mismatch_test/test_inputs.json"
      expected_outputs: "/tests/say_hello/mismatch_test/expected_outputs.json"
    file_type_mismatch:
      test_inputs: "/tests/say_hello/file_type_mismatch_test/test_inputs.json"
      expected_outputs: "/tests/say_hello/file_type_mismatch_test/expected_outputs.json"
    compress_file:
      test_inputs: "/tests/say_hello/compress_file_test/test_inputs.json"
      expected_outputs: "/tests/say_hello/compress_file_test/expected_outputs.json"
extract_stat:
  path: "/workflows/extract_stat.wdl"
  tests:
    simple:
      test_inputs: "/tests/extract_stat/simple_test/test_inputs.json"
      expected_outputs: "/tests/extract_stat/simple_test/expected_outputs.json"
    expect_fail:
      test_inputs: "/tests/extract_stat/expect_fail_test/test_inputs.json"
      expected_outputs: null
    array_shape_mismatch:
      test_inputs: "/tests/extract_stat/array_shape_mismatch_test/test_inputs.json"
      expected_outputs: "/tests/extract_stat/array_shape_mismatch_test/expected_outputs.json"
bad_workflow:
  path: "/workflows/bad_workflow.wdl"
  tests:
    bad_workflow:
      test_inputs: "/tests/bad_workflow/test_inputs.json"
      expected_outputs: "/tests/bad_workflow/expected_outputs.json"