on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -r requirements.txt
          wget https://github.com/broadinstitute/cromwell/releases/download/84/cromwell-84.jar
          python watt.py -e cromwell-84.jar -t simple, compress_file, expect_fail -p $(nproc)
      - run: |
          if python watt.py -e cromwell-84.jar -w say_hello -t mismatch; then
            exit 1
          fi