on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          pip install -r requirements.txt
          wget https://github.com/broadinstitute/cromwell/releases/download/84/cromwell-84.jar
          python watt.py -e cromwell-84.jar -t simple compress_file expect_fail -p $(nproc)
          echo "THE FOLLOWING TESTS SHOULD ALL FAIL"
          if python watt.py -e cromwell-84.jar -w say_hello -t mismatch; then
            echo "A test succeeded which should have passed.  Please look above for an unexpected success"
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w say_hello -t file_type_mismatch; then
            echo "A test succeeded which should have passed.  Please look above for an unexpected success"
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w extract_stat -t mismatch; then
            echo "A test succeeded which should have passed.  Please look above for an unexpected success"
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w extract_stat -t array_shape_mismatch; then
            echo "A test succeeded which should have passed.  Please look above for an unexpected success"
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w bad_workflow; then
            echo "A test succeeded which should have passed.  Please look above for an unexpected success"
            exit 1
          fi
