on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          wget -q https://github.com/broadinstitute/cromwell/releases/download/84/cromwell-84.jar
      - name: Run tests which should pass
        run:   python watt.py -e cromwell-84.jar -t simple compress_file expect_fail -p $(nproc)
      - name: Run tests which should fail
        run: |
          echo "THE FOLLOWING TESTS SHOULD ALL FAIL"
          if python watt.py -e cromwell-84.jar -w say_hello -t mismatch; then
            echo "Test mismatch for workflow say_hello succeeded which should not have passed."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w say_hello -t file_type_mismatch; then
            echo "Test file_type_mismatch for workflow say_hello succeeded which should not have passed."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w extract_stat -t mismatch; then
            echo "Test mismatch for workflow extract_stat succeeded which should not have passed."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w extract_stat -t array_shape_mismatch; then
            echo "Test array_shape_mismatch for workflow extract_stat succeeded which should not have passed."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w bad_workflow; then
            echo "Test for workflow bad_workflow succeeded which should not have passed."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w not_a_workflow; then
            echo "Test specifying non existent workflow not_a_workflow succeeded which should have raised exception."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -t not_a_test; then
            echo "Test specifying non existent test not_a_tes succeeded which should have raised exception."
            exit 1
          fi
          if python watt.py -e cromwell-84.jar -w say_hello extract_stat -t expect_fail; then
            echo "Test specifying non existent workflow/test combo say_hello:expect_fail succeeded which should have raised exception."
            exit 1
          fi
